services:
  postgres-usuarios:
    image: postgres:latest
    container_name: tecsup-postgres-usuarios
    restart: unless-stopped
    environment:
      POSTGRES_DB: usuarios_tokens_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tecsup-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usuarios_tokens_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  usuarios-service:
    build: .
    container_name: tecsup-usuarios-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      postgres-usuarios:
        condition: service_healthy
    networks:
      - tecsup-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  tecsup-network:
    driver: bridge
